blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/kunalbandale/web-highlighter-notes/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/kunalbandale/web-highlighter-notes#readme
    about: Please check the documentation first. 